# docker-compose.yml
version: '3'
services:
  asker-bot:
    build:
      context: tech_support_demo_bot
    container_name: asker_container

  helpdesk:
    build:
      context: tech_support_inference
    container_name: helpdesk_container
    volumes:
      - stats_database:/app/stats/

  landing:
    build:
      context: tech_support_landing
    container_name: landing_container
    ports:
      - "80:80"
    environment:
      - RAN_BY_DOCKER=1

volumes:
  stats_database:
  
